name: Build and release for official

on:
  push:
    tags:
      - "*.*.*"

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get version
        uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Create archive
        run: Compress-Archive -Path bse_converter.apk,readme.txt -Destination BSE_CONVERTER-${{ steps.tagName.outputs.tag }}.zip

      - name: Deploy to GitHub
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ github.event.repository.name }} official release
          draft: true
          files: |
            ./*.zip

  error_notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ failure() }}
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "Github actions build failed! <${{ github.server_url }}/${{ github.repository }}|${{ github.event.repository.name }}>のofficial releaseビルドが失敗しました。\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|対象のrun>お確認し、対応着手時・完了後は、本チャンネルにて経緯を報告ください。"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERT_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

